# Generated by Django 4.1.3 on 2022-11-28 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('executive_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('leadership_level', models.CharField(choices=[('1', 'National'), ('2', 'Union'), ('3', 'Zonal'), ('4', 'Fellowship')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.position')),
            ],
        ),
    ]
