# Generated by Django 4.1.3 on 2022-11-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='name',
            new_name='Full_name',
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
