# Generated by Django 4.1.3 on 2022-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_executive_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='position',
        ),
    ]
