# Generated by Django 4.1.3 on 2022-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_executive_leadership_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='executive_image',
            field=models.ImageField(blank=True, default='gnaas.jfif', null=True, upload_to=''),
        ),
    ]
