# Generated by Django 4.1.3 on 2022-12-01 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_executive_executive_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('mandate', models.TextField(blank=True, null=True)),
                ('date_of_assumption', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee_Member',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_service', models.DateField(blank=True, null=True)),
                ('gnaas_fellowship', models.CharField(blank=True, max_length=200, null=True)),
                ('local_church', models.CharField(blank=True, max_length=150, null=True)),
                ('local_church_location', models.CharField(blank=True, max_length=100, null=True)),
                ('local_church_elder', models.CharField(blank=True, max_length=100, null=True)),
                ('local_church_elder_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='current_gnaas_fellowship',
            new_name='gnaas_fellowship',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='current_local_church',
            new_name='local_church',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='current_local_church_elder',
            new_name='local_church_elder',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='current_local_church_elder_contact',
            new_name='local_church_elder_contact',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='current_local_church_location',
            new_name='local_church_location',
        ),
    ]
