# Generated by Django 4.1.3 on 2022-12-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_committee_committee_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee_member',
            name='affiliated_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.committee'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='mandate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
