# Generated by Django 4.1.3 on 2022-12-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_committee_member_affiliated_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee_member',
            name='image',
            field=models.ImageField(blank=True, default='gnaas.jfif', null=True, upload_to=''),
        ),
    ]
