# Generated by Django 4.1.3 on 2022-12-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_committee_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='year_of_service',
            new_name='date_of_service',
        ),
    ]
