# Generated by Django 4.1.3 on 2022-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_union_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
