# Generated by Django 4.1.3 on 2022-12-07 06:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_executive_leadership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 7, 6, 37, 46, 453994, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='union',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
