# Generated by Django 4.1.3 on 2022-12-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_union_created_alter_union_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
