# Generated by Django 4.1.3 on 2022-12-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_committee_id_alter_committee_member_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='post',
        ),
    ]
