# Generated by Django 4.1.3 on 2022-12-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_position_position_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='post',
            new_name='position',
        ),
    ]
