# Generated by Django 4.1.3 on 2022-12-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_post_position_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='president',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='app.executive'),
        ),
    ]
