# Generated by Django 4.1.3 on 2022-12-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_executive_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowship',
            old_name='chaplain',
            new_name='chaplain_or_patron',
        ),
        migrations.AlterField(
            model_name='executive',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('fellowship', models.CharField(max_length=150)),
                ('union', models.CharField(choices=[('SGUC', 'Southern Ghana Union'), ('NGUC', 'Northern Ghana Union')], max_length=100)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Chaplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('fellowship', models.CharField(max_length=150)),
                ('union', models.CharField(choices=[('SGUC', 'Southern Ghana Union'), ('NGUC', 'Northern Ghana Union')], max_length=100)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni_rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('gnaas_fellowship', models.CharField(max_length=150)),
                ('local_church', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('union', models.CharField(choices=[('SGUC', 'Southern Ghana Union'), ('NGUC', 'Northern Ghana Union')], max_length=100)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
    ]
