# Generated by Django 4.1.3 on 2022-12-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_chaplain_fellowship_chaplain_or_patron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_rep',
            name='union',
            field=models.CharField(choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chaplain',
            name='union',
            field=models.CharField(choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='union',
            field=models.CharField(blank=True, choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='union',
            field=models.CharField(choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=100),
        ),
    ]
