# Generated by Django 4.1.3 on 2022-12-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_alumni_rep_union_alter_chaplain_union_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='union',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='name',
            new_name='full_name',
        ),
    ]
