# Generated by Django 4.1.3 on 2022-12-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_full_name_union_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('cost', models.FloatField(max_length=40)),
                ('program_level', models.CharField(choices=[('National', 'National'), ('Union', 'Union'), ('Zone', 'Zone'), ('Fellowship', 'Fellowship')], max_length=100)),
            ],
        ),
    ]
