# Generated by Django 4.1.3 on 2022-12-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_zone_names_zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
