# Generated by Django 4.1.3 on 2022-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_executive_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_rep',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaplain',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fellowship',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patron',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
    ]
