# Generated by Django 4.1.3 on 2022-12-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alumni_rep_academic_year_chaplain_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone_name'),
        ),
    ]
