# Generated by Django 4.1.3 on 2022-12-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_fellowship_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_rep',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone_name'),
        ),
        migrations.AlterField(
            model_name='chaplain',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone_name'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone_name'),
        ),
    ]
