# Generated by Django 4.1.3 on 2022-12-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_committee_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='affiliated_union',
            field=models.CharField(blank=True, choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], max_length=200, null=True),
        ),
    ]
