# Generated by Django 4.1.3 on 2022-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_fellowship_digital_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='local_church_elder',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='local_church_elder_contact',
        ),
        migrations.AddField(
            model_name='executive',
            name='conference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
