# Generated by Django 4.1.3 on 2023-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_executive_local_church_elder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_rep',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chaplain',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='date_of_assumption',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='committee_member',
            name='date_of_service',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='date_of_service',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=100, null=True),
        ),
    ]
