# Generated by Django 4.1.3 on 2023-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_alumni_rep_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('messages_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
