# Generated by Django 4.1.3 on 2023-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
