# Generated by Django 4.1.3 on 2023-02-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_executive_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(choices=[('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
