# Generated by Django 4.1.3 on 2023-02-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='name',
        ),
    ]
