# Generated by Django 4.1.3 on 2023-02-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_file_name_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
    ]
