# Generated by Django 4.1.3 on 2023-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_fellowship_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowship',
            name='gender',
        ),
        migrations.AddField(
            model_name='fellowship',
            name='females',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellowship',
            name='males',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
