# Generated by Django 4.1.3 on 2023-03-07 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_rep',
            name='zone',
            field=models.CharField(choices=[('Southern Ghana Union', 'Southern Ghana Union'), ('Northern Ghana Union', 'Northern Ghana Union')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaplain',
            name='zone',
            field=models.CharField(choices=[('Central Ghana', 'Central Ghana'), ('South Central', 'South Central'), ('Mid South', 'Mid South'), ('Mid West', 'Mid West'), ('North Mission', 'North Mission'), ('Mid Central', 'Mid Central'), ('Ashanti South', 'Ashanti South'), ('Mountain View', 'Mountain View'), ('Mid North', 'Mid North'), ('Green View', 'Green View'), ('Mid South', 'Mid South'), ('Accra City', 'Accra City'), ('Pioneeer Ghana', 'Pioneeer Ghana'), ('West Central', 'West Central'), ('South West', 'South West'), ('Western North', 'Western North'), ('Volta Ghana', 'Volta Ghana'), ('East Ghana', 'East Ghana'), ('Meridian Ghana', 'Meridian Ghana'), ('Eastern View', 'Eastern View'), ('Diamond Field', 'Diamond Field')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='zone',
            field=models.CharField(blank=True, choices=[('Central Ghana', 'Central Ghana'), ('South Central', 'South Central'), ('Mid South', 'Mid South'), ('Mid West', 'Mid West'), ('North Mission', 'North Mission'), ('Mid Central', 'Mid Central'), ('Ashanti South', 'Ashanti South'), ('Mountain View', 'Mountain View'), ('Mid North', 'Mid North'), ('Green View', 'Green View'), ('Mid South', 'Mid South'), ('Accra City', 'Accra City'), ('Pioneeer Ghana', 'Pioneeer Ghana'), ('West Central', 'West Central'), ('South West', 'South West'), ('Western North', 'Western North'), ('Volta Ghana', 'Volta Ghana'), ('East Ghana', 'East Ghana'), ('Meridian Ghana', 'Meridian Ghana'), ('Eastern View', 'Eastern View'), ('Diamond Field', 'Diamond Field')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='zone',
            field=models.CharField(choices=[('Central Ghana', 'Central Ghana'), ('South Central', 'South Central'), ('Mid South', 'Mid South'), ('Mid West', 'Mid West'), ('North Mission', 'North Mission'), ('Mid Central', 'Mid Central'), ('Ashanti South', 'Ashanti South'), ('Mountain View', 'Mountain View'), ('Mid North', 'Mid North'), ('Green View', 'Green View'), ('Mid South', 'Mid South'), ('Accra City', 'Accra City'), ('Pioneeer Ghana', 'Pioneeer Ghana'), ('West Central', 'West Central'), ('South West', 'South West'), ('Western North', 'Western North'), ('Volta Ghana', 'Volta Ghana'), ('East Ghana', 'East Ghana'), ('Meridian Ghana', 'Meridian Ghana'), ('Eastern View', 'Eastern View'), ('Diamond Field', 'Diamond Field')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Zone_Name',
        ),
    ]
